import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Headline } from '@/components/Headline/Headline'
import { LocaleProvider } from '@/i18n/locale-provider'
import { getLocale } from '@/i18n/server'
import '../styles/main.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = getLocale()

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <LocaleProvider value={locale}>
          <AntdRegistry>
            <Headline />
            {children}
          </AntdRegistry>
        </LocaleProvider>
      </body>
    </html>
  )
}
