import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header/Header'
import '../styles/main.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header siteUrl={process.env.NEXT_PUBLIC_BASE_URL || 'https://storygen-fun.vercel.app'} />
        {children}
      </body>
    </html>
  )
}
